# Accessing the First and Last row of a 2-D NumPy array

In [2]:

import numpy as np 

arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]]) 

print("Orginal Array :") 
print(arr) 

res_arr = arr[[0,2]] 
print("\nAccessed Rows :") 
print(res_arr)


Orginal Array :
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Rows :
[[10 20 30]
 [70 88 94]]


# Accessing the Middle row of 2-D NumPy array

In [3]:
# Importing
import numpy as np 



arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]]) 

print("Given Array :") 
print(arr) 

# Access the Middle row
res_arr = arr[1] 
print("\nAccessed Row :") 
print(res_arr)


Given Array :
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Row :
[40  5 66]


# Accessing the Last three rows of 2-D NuNumPy py array

In [5]:
import numpy as np 

arr = np.array([[10, 20, 30], 
                [40, 5, 66], 
                [70, 88, 94]]) 

print("Given Array :") 
print(arr) 


res_arr = arr[[1, 2]]  
print("\nAccessed Rows :") 
print(res_arr)


Given Array :
[[10 20 30]
 [40  5 66]
 [70 88 94]]

Accessed Rows :
[[40  5 66]
 [70 88 94]]


# Accessing the First two rows of a 2-D NumPy array

In [6]:
import numpy as np 

arr = np.array([[1, 20, 3, 1], 
                [40, 5, 66, 7], 
                [70, 88, 9, 11], 
                [80, 100, 50, 77], 
                [1, 8.5, 7.9, 4.8]]) 

print("Given Array :") 
print(arr) 

res_arr = arr[:2]  # Slicing to select the first two rows
print("\nAccessed Rows :") 
print(res_arr)


Given Array :
[[  1.   20.    3.    1. ]
 [ 40.    5.   66.    7. ]
 [ 70.   88.    9.   11. ]
 [ 80.  100.   50.   77. ]
 [  1.    8.5   7.9   4.8]]

Accessed Rows :
[[ 1. 20.  3.  1.]
 [40.  5. 66.  7.]]
