In [3]:
# importing 
import numpy as np

# creating a 3-D Numpy array
n_array = np.array([[0, 2, 3],
                    [4, 1, 0],
                    [0, 0, 2]])

print("Original array:")
print(n_array)


# using np.argwhere()
print("\nIndices of null elements:")
null = np.argwhere(n_array == 0)

print(null)

# 0 is at position (0, 0) (1st row, 1st column)
# 0 is at position (1, 2) (2nd row, 3rd column)
# 0 is at position (2, 0) (3rd row, 1st column)
# 0 is at position (2, 1) (3rd row, 2nd column)

Original array:
[[0 2 3]
 [4 1 0]
 [0 0 2]]

Indices of null elements:
[[0 0]
 [1 2]
 [2 0]
 [2 1]]
