In [4]:
import numpy as np 

a1 = np.array([[[11, 25, 7], [30, 45, 55], [20, 45, 7]], 
                [[50, 65, 8], [70, 85, 10], [11, 22, 33]], 
                [[19, 69, 36], [1, 5, 24], [4, 20, 9]]]) 

print("Array 1:") 
print(a1) 

a2 = np.array([[1, 15, 10], 
                [6, 40, 50], 
                [11, 5, 10]]) 

print("Array 2:") 
print(a2) 

print("Take 1, 15, 10, 6, 40 and 50 from Array 2 and put them in the 1st, 3rd, 5th, 9th, 11th, and 15th positions of Array 1")

# Using the put function to place elements from a2 into a1 at the specified positions
a1.put([0, 2, 4, 8, 10, 14], [1, 15, 10, 6, 40, 50]) 

print("Resultant Array:")
print(a1)

Array 1:
[[[11 25  7]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20  9]]]
Array 2:
[[ 1 15 10]
 [ 6 40 50]
 [11  5 10]]
Take 1, 15, 10, 6, 40 and 50 from Array 2 and put them in the 1st, 3rd, 5th, 9th, 11th, and 15th positions of Array 1
Resultant Array:
[[[ 1 25 15]
  [30 10 55]
  [20 45  6]]

 [[50 40  8]
  [70 85 50]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20  9]]]
