In [4]:
#impor
import numpy as np

arr=np.arange(6).reshape(3,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
target_arr = np.where (arr<=5)
target_arr

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 0, 1], dtype=int64))

In [9]:
arr[target_arr]

array([0, 1, 2, 3, 4, 5])