# Create a Numpy Array with Random Values

In [4]:
import numpy as np

random_array = np.random.rand(3, 4)

print("Random Array:\n", random_array)

Random Array:
 [[0.86563391 0.38079164 0.04484007 0.07135402]
 [0.31776261 0.73990935 0.65626554 0.02394086]
 [0.99169445 0.71962304 0.58398826 0.69743585]]


# Choose Elements from a List with Different Probability

In [5]:
elements = ['a', 'b', 'c', 'd']
probabilities = [0.1, 0.2, 0.5, 0.2]

# Choose one element based on the given probabilities
chosen_element = np.random.choice(elements, p = probabilities)

print("\nChosen Element with Probability:", chosen_element)


Chosen Element with Probability: c


# Get Weighted Random Choice

In [6]:
weights = [0.05, 0.15, 0.7, 0.1]

weighted_choices = np.random.choice(elements, size=3, replace=True, p=weights)

print("\nWeighted Random Choices:", weighted_choices)


Weighted Random Choices: ['c' 'c' 'b']
