# Get the Indices of the Sorted 2D Array 

In [7]:
import numpy as np

arr = np.array([[10, 40, 30], 
                [20, 50, 60]])

sorted_indices = np.argsort(arr, axis=1) # axis=0 for column-wise

print("Original Array:")
print(arr)
print("\nIndices of sorted array (row-wise):")
print(sorted_indices)


Original Array:
[[10 40 30]
 [20 50 60]]

Indices of sorted array (row-wise):
[[0 2 1]
 [0 1 2]]


# Find the k Smallest Values of a 2D NumPy Array

In [2]:
import numpy as np

arr = np.array([[7, 1, 3, 5, 2], 
                [8, 6, 4, 9, 0]])

k = 2  

k_smallest_indices = np.argsort(arr, axis=1)[:, :k]

k_smallest_values = np.take_along_axis(arr, k_smallest_indices, axis=1)

print("k Smallest Values (row-wise):")
print(k_smallest_values)

k Smallest Values (row-wise):
[[1 2]
 [0 4]]


# Get the n Largest Values of a 2D NumPy Array

In [3]:
import numpy as np

arr = np.array([[7, 1, 3, 5, 2], 
                [8, 6, 4, 9, 0]])

n = 2 

n_largest_indices = np.argsort(arr, axis=1)[:, -n:]

n_largest_values = np.take_along_axis(arr, n_largest_indices, axis=1)

print("n Largest Values (row-wise):")
print(n_largest_values)


n Largest Values (row-wise):
[[5 7]
 [8 9]]


#  Sort the Values in a 2D Matrix

In [4]:
import numpy as np

matrix = np.array([[3, 1, 4], 
                   [9, 5, 6]])

# Sort each row
sorted_matrix = np.sort(matrix, axis=1)

print("Row-wise Sorted Matrix:")
print(sorted_matrix)


Row-wise Sorted Matrix:
[[1 3 4]
 [5 6 9]]


# Filter Out Integers from a Float 2D NumPy Array

In [8]:
import numpy as np

arr = np.array([[1.2, 2.5, 3.0], 
                [4.7, 5.0, 6.8]])

# Filter out integers
non_integers = arr[arr % 1 != 0].reshape(arr.shape[0], -1)

print("Non-integer Values in 2D Array:")
print(non_integers)

Non-integer Values in 2D Array:
[[1.2 2.5]
 [4.7 6.8]]
