In [1]:
import numpy as np

#empty arry
empty_array_2d = np.empty((3, 4))
print(empty_array_2d)


[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 1.86921143e-306]]


In [2]:
# full arry
full_array_2d = np.full((3, 4), 5)
print(full_array_2d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [3]:
#we create an empty array of 3X4 and a full array of 3X3 of INTEGER type.


# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)

# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)


Empty Array
[[7209071 5111900 4784214 4784196]
 [2097217 7733326 4980804 5439561]
 [3866706 3801155 5242972 7274610]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [4]:
#we create an empty array of 4X2 and a full array of 4X3 of INTEGER and FLOAT type.


# Create an empty array
empa = np.empty([4, 2])
print("Empty Array")
print(empa)

# Create a full array
flla = np.full([4, 3], 95)
print("\n Full Array")
print(flla)


Empty Array
[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 2.33646845e-307]
 [1.42413555e-306 1.78019082e-306]
 [1.37959740e-306 2.29178686e-312]]

 Full Array
[[95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]]
