In [7]:
import numpy as np

main_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])


join_array = np.array([[100],[200],[300]])


In [6]:
#Using np.append()
column = np.append (main_array,join_array,axis=1)

column

array([[  1,   2,   3, 100],
       [ 45,   4,   7, 200],
       [  9,   6,  10, 300]])

In [10]:
# Using np.concatenate
concat = np.concatenate([main_array,join_array],axis=1)
concat

array([[  1,   2,   3, 100],
       [ 45,   4,   7, 200],
       [  9,   6,  10, 300]])

In [13]:
#Using np.insert()

insert_values = np.insert (main_array,0,join_array,axis=1)
insert_values

array([[100, 200, 300,   1,   2,   3],
       [100, 200, 300,  45,   4,   7],
       [100, 200, 300,   9,   6,  10]])

In [16]:
#Using np.hstack()  
new = np.array([1, 2, 3])
h_stack = np.hstack((main_array, np.atleast_2d(new).T))
h_stack

array([[ 1,  2,  3,  1],
       [45,  4,  7,  2],
       [ 9,  6, 10,  3]])